### ISSUE TITLE
Worker: retry in case of timeout when calling log_start_tuple seems buggy

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra-backend#72]
Traceback:
```
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] [2019-12-09 21:33:15,334: ERROR/ForkPoolWorker-1] exception calling callback for <Future at 0x7f50303a4908 state=finished raised _Rendezvous>
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] Traceback (most recent call last):
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     result = self.fn(*self.args, **self.kwargs)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/local/lib/python3.6/dist-packages/aiogrpc/utils.py", line 126, in _next
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     return next(self._iterator)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 392, in __next__
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     return self._next()
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 561, in _next
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     raise self
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] 	status = StatusCode.CANCELLED
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] 	details = "Locally cancelled by application!"
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] 	debug_error_string = "None"
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] >
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] During handling of the above exception, another exception occurred:
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] Traceback (most recent call last):
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     callback(self)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/lib/python3.6/asyncio/futures.py", line 417, in _call_set_state
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     dest_loop.call_soon_threadsafe(_set_state, destination, source)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/lib/python3.6/asyncio/base_events.py", line 637, in call_soon_threadsafe
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     self._check_closed()
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     raise RuntimeError('Event loop is closed')
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] RuntimeError: Event loop is closed
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend]
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend]
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend]   [SQL Queries for] /composite_traintuple/7d3419fa32def5678c555ce985305b12faa1e5c2cbc9cff449f4d5a17e3d0b84/
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend]
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend]   [0.003] SELECT authtoken_token.key,  authtoken_token.user_id,  authtoken_token.created,  auth_user.id,  auth_user.password,  auth_user.last_login,  auth_user.is_superuser,  auth_user.username,  auth_user.first_name,  auth_user.last_name,  auth_user.email,  auth_user.is_staff,  auth_user.is_active,  auth_user.date_joined FROM authtoken_token INNER JOIN auth_user ON (authtoken_token.user_id = auth_user.id) WHERE authtoken_token.key = '41c18852d55e6dfdc751f75c7f84bdb850a7f0cc'
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend]
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend]   [TOTAL TIME: 0.003 seconds (1 queries)]
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend] [09/Dec/2019 21:33:15] "GET /composite_traintuple/7d3419fa32def5678c555ce985305b12faa1e5c2cbc9cff449f4d5a17e3d0b84/ HTTP/1.1" 200 1806
[backend-org-1-substra-backend-server-6b867c94c-p7t5q substra-backend] [09/Dec/2019 21:33:16] "GET /readiness HTTP/1.1" 200 2
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] [2019-12-09 21:33:17,333: WARNING/ForkPoolWorker-1] Function invoke_ledger failed (<class 'substrapp.ledger_utils.LedgerTimeout'>): waitForEvent timed out. retrying in 2s
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] [2019-12-09 21:33:17,386: INFO/ForkPoolWorker-1] DISCOVERY: adding channel peers query
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] [2019-12-09 21:33:17,386: INFO/ForkPoolWorker-1] DISCOVERY: adding config query
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] [2019-12-09 21:33:17,387: INFO/ForkPoolWorker-1] DISCOVERY: adding chaincodes/collection query
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] [2019-12-09 21:33:17,468: ERROR/ForkPoolWorker-1] Task substrapp.tasks.tasks.prepare_tuple[7d3419fa32def5678c555ce985305b12faa1e5c2cbc9cff449f4d5a17e3d0b84] raised unexpected: cannot update traintuple 7d3419fa32def5678c555ce985305b12faa1e5c2cbc9cff449f4d5a17e3d0b84 - status already doing
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] Traceback (most recent call last):
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 382, in trace_task
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     R = retval = fun(*args, **kwargs)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 641, in __protected_call__
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     return self.run(*args, **kwargs)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/src/app/substrapp/tasks/tasks.py", line 428, in prepare_tuple
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     log_start_tuple(tuple_type, subtuple['key'])
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 98, in _wrapper
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     return fn(*args, **kwargs)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 320, in log_start_tuple
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     sync=True)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 98, in _wrapper
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     return fn(*args, **kwargs)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 210, in invoke_ledger
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     response = call_ledger('invoke', fcn=fcn, args=args, kwargs=params)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 187, in call_ledger
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker]     raise exception_class.from_response(response)
[backend-org-2-substra-backend-worker-56c79d57bd-tdv9b worker] substrapp.ledger_utils.LedgerResponseError: cannot update traintuple 7d3419fa32def5678c555ce985305b12faa1e5c2cbc9cff449f4d5a17e3d0b84 - status already doing
```

Seen while executing the test (random failure): `tests/test_execution_compute_plan.py::test_compute_plan_aggregate_composite_traintuples`

**Comment by samlesu** [comment]
Similar bug seen with the populate:
```
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker] [2019-12-10 15:36:48,688: WARNING/ForkPoolWorker-1] Function invoke_ledger failed (<class 'substrapp.ledger_utils.LedgerTimeout'>): waitForEvent timed out. retrying in 2s
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker] [2019-12-10 15:36:48,710: INFO/ForkPoolWorker-1] DISCOVERY: adding channel peers query
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker] [2019-12-10 15:36:48,710: INFO/ForkPoolWorker-1] DISCOVERY: adding config query
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker] [2019-12-10 15:36:48,710: INFO/ForkPoolWorker-1] DISCOVERY: adding chaincodes/collection query
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker] [2019-12-10 15:36:48,745: ERROR/ForkPoolWorker-1] Task substrapp.tasks.tasks.prepare_tuple[b835634d3ffb38fa98101619717aa07b62051ab2caa7be784dd1cfaef374d99a] raised unexpected: update testtuple b835634d3ffb38fa98101619717aa07b62051ab2caa7be784dd1cfaef374d99a failed: cannot change status from doing to doing
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker] Traceback (most recent call last):
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 382, in trace_task
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]     R = retval = fun(*args, **kwargs)
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 641, in __protected_call__
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]     return self.run(*args, **kwargs)
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]   File "/usr/src/app/substrapp/tasks/tasks.py", line 428, in prepare_tuple
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]     log_start_tuple(tuple_type, subtuple['key'])
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 98, in _wrapper
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]     return fn(*args, **kwargs)
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 320, in log_start_tuple
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]     sync=True)
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 98, in _wrapper
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]     return fn(*args, **kwargs)
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 210, in invoke_ledger
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]     response = call_ledger('invoke', fcn=fcn, args=args, kwargs=params)
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]   File "/usr/src/app/substrapp/ledger_utils.py", line 187, in call_ledger
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker]     raise exception_class.from_response(response)
[backend-org-1-substra-backend-worker-6d46485f8f-bvqp9 worker] substrapp.ledger_utils.LedgerResponseError: update testtuple b835634d3ffb38fa98101619717aa07b62051ab2caa7be784dd1cfaef374d99a failed: cannot change status from doing to doing
```
